# 200 hooks (one per post), grouped by topic.
# The generator interleaves them round-robin so no two consecutive posts share a topic.

HOOKS = {
    "xscriptor": [
        "Escribir es mi forma de compilar ideas.",
        "Un ensayo puede ser también un sistema de diseño.",
        "De una idea sobre la superposición de circunstancias a 36 piezas generadas.",
        "Mi portfolio no muestra trabajo: muestra criterio.",
        "Aprender en público tiene un coste y un retorno: los dos son reales.",
        "Diseño con tipografía, retícula y un solo acento. Nada más.",
        "Generé 100 fondos con matemáticas y una paleta de 6 colores.",
        "El código sin contexto se olvida; por eso documento todo.",
        "¿Por qué leo ensayos para escribir mejor software?",
        "Mi ecosistema: front-end, accesibilidad, tipografía y ensayo.",
        "Cuando una idea no cabe en un hilo, se convierte en proyecto.",
        "Sustraer es la operación de diseño más difícil.",
        "Números en Doto, texto en Space. El resto es silencio.",
        "La coherencia entre proyectos es mi métrica favorita.",
        "Publicar un experimento fallido también es documentar.",
        "Tres filtros para cada proyecto: ¿enseña?, ¿funciona?, ¿aguanta?",
        "Escribo en dos idiomas para pensar dos veces.",
        "Formalizar una intuición es el paso que casi nadie da.",
        "¿Qué pasa cuando tratas un tema filosófico como un problema de diseño?",
        "La estética no decora: comunica.",
    ],
    "typescript": [
        "Tu tsconfig puede atrapar más bugs que una semana de code review.",
        "any no es un tipo: es apagar el compilador con estilo.",
        "Los estados imposibles no se testean: se tipan.",
        "Si tu API miente, TypeScript no puede salvarte: valida en el borde.",
        "as es una promesa que le haces al compilador. Cúmplela.",
        "5 flags de tsconfig que suben la calidad de un proyecto entero.",
        "El tipado bueno documenta; el tipado heroico estorba.",
        "¿Por qué satisfies cambió mi forma de escribir configuración?",
        "Los genéricos en exceso convierten el código en un acertijo.",
        "Error clásico: confundir unknown con any y perder la red de seguridad.",
        "Un never bien usado detecta el caso que olvidaste cubrir.",
        "strict: true no basta: estas dos opciones extra duelen y valen la pena.",
        "Tipar JSON de terceros sin validación es firmar un cheque en blanco.",
        "Del JS al TS sin dolor: migración incremental en 6 pasos.",
        "¿Cuánto tarda tu tsc --noEmit? Si pasa de 10 s, hay plan.",
        "Los tipos también se refactorizan: señales de un sistema enfermo.",
        "El mejor tipo es el que hace imposible el uso incorrecto.",
        "enum vs union: por qué casi siempre deberías elegir la union.",
        "Inferencia primero; anotación cuando aporta contexto.",
        "TypeScript en backend: lo que cambia cuando el runtime es Node.",
    ],
    "web": [
        "Tu LCP no mejora con más servidor, sino con menos bytes.",
        "El layout shift se arregla antes de la primera línea de CSS.",
        "HTML semántico: la optimización más barata que existe.",
        "¿Mides INP o todavía miras solo el First Paint?",
        "Una imagen hero sin fetchpriority es una oportunidad perdida.",
        "El usuario no espera 3 s: se va antes de que cargue tu spinner.",
        "CSS lógico y soporte RTL sin duplicar hojas de estilo.",
        "¿Cuánto JavaScript envías para mostrar texto?",
        "Formularios: validación en cliente para UX, en servidor para verdad.",
        "Service workers: resiliencia offline mal entendida = versiones viejas.",
        "Fuentes variables, subset y font-display bien elegido.",
        "El estado en la URL: enlaces compartibles y navegación predecible.",
        "Componentes que funcionan sin JS: la prueba de fuego del front.",
        "Medir con datos de campo o engañarte con el laboratorio.",
        "La accesibilidad también es rendimiento: menos DOM, menos caos.",
        "¿Cuánto de tu interfaz es estado y cuánto es HTML mal organizado?",
    ],
    "accesibilidad": [
        "4.5:1 de contraste no es una recomendación: es el mínimo para leer.",
        "Si el foco desaparece, el teclado desaparece con él.",
        "Los div con onclick son botones rotos para media humanidad.",
        "Los errores de formulario deben explicarse, no solo pintarse de rojo.",
        "5 minutos de navegación por teclado revelan más que una auditoría automática.",
        "Un lector de pantalla no adivina: describe imágenes por su función.",
        "Modales: foco atrapado, Escape y devolver el foco al origen.",
        "El color no puede ser el único portador de información.",
        "Skip links: 20 minutos que ahorran cientos de tabulaciones.",
        "lang correcto: la diferencia entre una voz decente y una incoherente.",
        "Reduce el movimiento y respeta las preferencias del sistema.",
        "Etiquetas visibles: el placeholder no es una etiqueta.",
        "Prueba con teclado, zoom al 200% y lector: tres puertas, mismo producto.",
        "La accesibilidad se diseña en Figma, no se parchea al final.",
        "Contenido claro también es accesibilidad cognitiva.",
        "Un error de accesibilidad es un error de producto, no un extra.",
    ],
    "usabilidad": [
        "Si hay que explicar el botón de guardar, el diseño falla.",
        "Reconocer es más fácil que recordar: opciones visibles, menús con criterio.",
        "Un formulario más corto convierte más que un formulario más bonito.",
        "El estado vacío es la primera impresión de tu producto.",
        "Feedback en menos de 100 ms: la interfaz debe tener pulso.",
        "5 usuarios detectan el 80% de los problemas de usabilidad.",
        "El texto de los botones debería ser un verbo concreto.",
        "Mide tareas completadas, no clics.",
        "Los patrones conocidos ahorran aprendizaje: innova donde importa.",
        "Si el buscador no perdona un typo, no está terminado.",
        "La carga cognitiva se acumula: cada decisión nueva tiene coste.",
        "Un error debe decir qué pasó, qué hacer y cómo seguir.",
        "El onboarding no reemplaza a un diseño comprensible.",
        "Lo que no se puede deshacer debe poder confirmarse.",
        "Diseñar para el peor día del usuario, no para su mejor momento.",
        "La usabilidad se nota en soporte: cada ticket es una pista.",
    ],
    "programacion": [
        "El código se lee 10 veces más de lo que se escribe.",
        "Nombrar bien es el 50% de diseñar.",
        "Una función que hace dos cosas se testea cuatro veces.",
        "Los tests que importan describen comportamiento, no implementación.",
        "Duplicar está bien dos veces; a la tercera abstrae con evidencia.",
        "Reproducibilidad antes que fe: contenedores, versiones y lockfiles.",
        "Los commits cuentan una historia: qué cambia y por qué.",
        "Los errores silenciosos son deuda técnica emocional.",
        "Revisar código es enseñar; aprobar sin comentar desperdicia contexto.",
        "Escribe el contrato antes que la implementación.",
        "Si no puedes explicarlo en una frase, aún no lo entiendes.",
        "Refactoriza con red: tests primero, cambios pequeños después.",
        "La deuda técnica es un préstamo: decide cuándo pagas intereses.",
        "Optimiza después de medir; antes es adivinar.",
        "Los logs son para el futuro tú: escribe como si tuvieras prisa.",
        "La simplicidad no es hacer menos: es quitar lo que sobra.",
    ],
    "javascript": [
        "structuredClone ya está en el runtime: deja de clonar con JSON.",
        "?? y || no son sinónimos: 0 y cadena vacía te lo pueden recordar.",
        "Object.hasOwn, at(-1) y groupBy: el JS moderno que ya puedes usar.",
        "Módulos ES: adiós a las variables globales accidentales.",
        "Promise.allSettled cuando un fallo no debe tumbar el lote.",
        "AbortController: cancelar sin dejar promesas huérfanas.",
        "Intl resuelve fechas, números y plurales sin librerías.",
        "Campos privados con # en clases: encapsulación real.",
        "El orden de la cola de microtareas explica tus bugs async.",
        "Generadores para procesar streams sin cargar todo en memoria.",
        "WeakMap para metadatos sin fugas de memoria.",
        "Array.fromAsync convierte flujos asíncronos en arrays legibles.",
        "Top-level await: inicialización más honesta, con coste.",
        "El switch sin break no es un misterio: es un error buscando silencio.",
        "for await versus cargar todo: decide por tamaño, no por gusto.",
        "Los getters pueden ocultar trabajo pesado: úsalos con cabeza.",
    ],
    "vscode": [
        "Cmd/Ctrl+P con @ salta a símbolos: adiós al scroll eterno.",
        "Perfiles de VS Code: separa trabajo, estudio y charlas sin ruido.",
        "Settings Sync te devuelve el entorno en cinco minutos.",
        "tsc --watch + Problems: feedback continuo sin cambiar de ventana.",
        "formatOnSave solo es útil si la config vive en el repo.",
        "Multi-root workspaces: monorepos sin tres ventanas abiertas.",
        "GitLens y el Timeline responden quién y por qué sin salir del editor.",
        "Tasks: convierte correr los tests en una combinación de teclas.",
        "Remote SSH y Containers: desarrolla en el entorno real sin ensuciar el local.",
        "Un settings.json compartido alinea al equipo sin discusiones.",
        "Zen mode y centrar el layout: menos ventana, más foco.",
        "code --diff a b para comparaciones rápidas y limpias.",
        "Snippets propios: escribe el boilerplate una vez.",
        "search.exclude acelera búsquedas en proyectos gigantes.",
        "El terminal integrado con perfiles por proyecto ahorra contextos.",
        "Sticky scroll y breadcrumbs: orientación en archivos largos.",
    ],
    "extensiones": [
        "Una extensión debe fallar en silencio o avisar claro; nunca dejar dudas.",
        "engines.vscode evita llamar APIs que no existen en la versión del usuario.",
        "Activación perezosa: tu extensión no debe arrancar el editor más lento.",
        "Comandos idempotentes: dos ejecuciones, un solo estado consistente.",
        "OutputChannel para logs: console.log se pierde al cerrar el panel.",
        "README con GIF y atajos: multiplica instalaciones sin tocar el código.",
        "Cláusulas when: comandos que aparecen solo donde tienen sentido.",
        "Tests con vscode-test: simulan al usuario y atrapan regresiones.",
        "Publicar con vsce y semver: el marketplace castiga versiones rotas.",
        "Un icono legible a 24 px vale más que un logo detallado.",
        "Telemetría opcional y anónima: mide sin invadir.",
        "WebView solo cuando el árbol nativo no alcanza.",
        "CHANGELOG por versión: la documentación que sí se lee.",
        "Valores por defecto sensatos: cero setup para empezar.",
        "Localización con l10n: el marketplace es global por defecto.",
        "Responder issues en 48 h: la comunidad es parte del producto.",
    ],
    "ecosistema": [
        "pnpm + workspaces: enlaces deterministas y deduplicación en monorepos.",
        "Biome y oxlint cuando ESLint se convierte en cuello de botella.",
        "Vitest reutiliza tu config de Vite: deja de mantener dos mundos.",
        "Turborepo y Nx: decide por caché y orquestación, no por moda.",
        "engines en package.json: documenta y bloquea la versión real de Node.",
        "Renovate con reglas: menos ruido de PRs y dependencias al día.",
        "tsup y esbuild para librerías: builds en milisegundos.",
        "ESM primero, CJS por compatibilidad: planifica la doble salida.",
        "corepack fija el package manager por proyecto sin globales.",
        "Lockfile en CI: todos ejecutan exactamente lo mismo.",
        "Devcontainers: instala esto se convierte en abrir un contenedor.",
        "npm audit --audit-level=high en CI, no 40 avisos informativos.",
        "Un script check que corre tipos, lint y tests: la puerta única.",
        "Monorepo sí, pero con límites: paquetes con dueño y contrato claro.",
        "Versionado semántico real: los breaking changes se anuncian, no se descubren.",
        "Menos dependencias: cada una es una promesa que otro mantiene.",
    ],
    "distros": [
        "Hyprland: Wayland, tiling y atajos; el escritorio como herramienta.",
        "Debian estable en servidores: aburrido es un cumplido.",
        "Fedora adelanta tecnología; tú pones la disciplina.",
        "Arch no es difícil, es explícito: cada decisión es tuya.",
        "Tumbleweed + snapper: rolling release con red de seguridad.",
        "NixOS convierte tu sistema en código reproducible.",
        "Mint para empezar, Ubuntu LTS para soporte, Arch para control.",
        "El mejor distro combina tus drivers, tu flujo y tu tolerancia al cambio.",
        "Snapshot antes de actualizar: 10 minutos que salvan una tarde.",
        "KDE Plasma 6 en Wayland ya es de diario.",
        "Live USB: prueba hardware y decisiones antes de instalar.",
        "Dotfiles versionados: cambiar de distro es una tarde, no un drama.",
        "Repos oficiales primero; PPAs y AUR con criterio.",
        "Wayland no es futuro: es presente con matices por hardware.",
        "Un sistema limpio se nota en el arranque; mide, no supongas.",
        "Cada distro enseña algo: elige la que te enseñe lo que te falta.",
    ],
    "carrera": [
        "Tu portfolio es el README de tu criterio.",
        "Aprender en público acelera más que esperar a ser experto.",
        "Escribir bien y leer código ajeno: la mejor inversión temprana.",
        "Un CV elige una historia; no lo puede contar todo.",
        "De junior a senior: decides y explicas, no acumulas frameworks.",
        "Fundamentos primero: duran más que cualquier versión.",
        "Pide feedback concreto, no aprobación.",
        "La entrevista evalúa comunicación bajo presión: practícala en voz alta.",
        "Documenta lo que aprendes: tu mejor material sale del trabajo real.",
        "Publicar con honestidad combate el síndrome del impostor.",
        "Diseño, accesibilidad y producto multiplican tu impacto como dev.",
        "30 minutos diarios ganan a un curso intensivo de un fin de semana.",
        "Decir no sé con criterio genera más confianza, no menos.",
        "Los hábitos se notan a cinco años; las herramientas, a cinco días.",
        "Especialízate sin cerrarte: contexto y profundidad.",
        "Escribe post-mortems: los errores documentados valen oro.",
    ],
}
