# Content data for the LinkedIn posts.
# Each topic: image label, hashtags, subtitles, and a bank of concrete ideas
# (combined 4 at a time with a different rotation per post).

TOPICS = {
    "typescript": {
        "label": "TYPESCRIPT",
        "hashtags": ["#TypeScript", "#JavaScript", "#DesarrolloWeb"],
        "subs": ["Tipos que documentan", "Del tipado al detalle", "Menos any, más intención"],
        "items": [
            "`strict: true` no es un lujo: añade `noUncheckedIndexedAccess` y `exactOptionalPropertyTypes` y verás errores reales de tu código, no del compilador.",
            "`satisfies` valida una forma sin ensanchar el tipo: ideal para configuración donde quieres inferencia literal y comprobación a la vez.",
            "Los tipos discriminados eliminan estados imposibles: una propiedad `kind` y un `switch` exhaustivo con `never` te dan seguridad total.",
            "`unknown` es el tipo correcto para entrada externa; `any` desactiva el sistema y contamina todo lo que toca.",
            "Las `const assertions` convierten arrays y objetos en literales de solo lectura: perfectas para tablas de configuración.",
            "Los `template literal types` permiten tipar claves compuestas, como rutas `api/${string}` o eventos `on${Capitalize<string>}`.",
            "Los mapped types evitan duplicar interfaces: si cambia la fuente, el resto se recalcula solo.",
            "Conditional types e `infer` resuelven el tipado de funciones genéricas sin casts manuales.",
            "`import type` deja claro qué se borra al compilar y evita ciclos en tiempo de ejecución.",
            "Con `moduleResolution: \"bundler\"` y `verbatimModuleSyntax` tu código es más predecible al cambiar de bundler.",
            "`tsc --noEmit` en CI es la barrera más barata: cuesta segundos y evita despliegues rotos.",
            "Si un tipo aparece una sola vez, probablemente no necesita ser un parámetro genérico.",
            "`enum` casi nunca: las uniones de literales son más simples, más seguras y no generan código en runtime.",
            "Inferencia primero; anota cuando aporte contexto o cuando el contrato deba ser explícito.",
            "Tipar JSON de terceros sin validación en el borde es firmar un cheque en blanco: `zod` y compañía existen por algo.",
            "Los tipos también se refactorizan: si un cambio pequeño rompe veinte archivos, el sistema de tipos está enfermo.",
        ],
    },
    "xscriptor": {
        "label": "XSCRIPTOR",
        "hashtags": ["#Xscriptor", "#AprenderEnPúblico", "#DesarrolloWeb"],
        "subs": ["Aprender en público", "Ensayo y sistema", "Cuaderno abierto"],
        "items": [
            "Escribir es mi forma de compilar ideas: publicar es la última fase de entender algo.",
            "Un ensayo puede convertirse en un sistema de diseño si aceptas formalizarlo y reducirlo.",
            "De una idea sobre la superposición de circunstancias salieron 36 piezas generadas con matemáticas y una paleta de seis colores.",
            "Mi portfolio no muestra trabajo: muestra criterio y decisiones.",
            "Aprender en público tiene un coste y un retorno; los dos son reales y los dos se gestionan.",
            "Diseño con tipografía, una retícula y un solo acento. Todo lo demás es negociable.",
            "Generé más de cien fondos con curvas de nivel, puntos y una única regla: sustraer antes de añadir.",
            "El código sin contexto se olvida; por eso documento cada experimento aunque no salga bien.",
            "Leo ensayos para escribir mejor software: pensar un problema con palabras ordena las soluciones.",
            "Mi ecosistema es front-end, accesibilidad, tipografía y ensayo; todo se conecta por el mismo método.",
            "Cuando una idea no cabe en un hilo, se convierte en proyecto.",
            "Sustraer es la operación de diseño más difícil y la que más se nota.",
            "Doto para números, Space para texto, y el resto es silencio.",
            "La coherencia entre proyectos es mi métrica favorita: más que la cantidad o la novedad.",
            "Publicar un experimento fallido también es documentar: deja un patrón reutilizable.",
            "Todo pasa por tres filtros: ¿enseña?, ¿funciona?, ¿se sostiene con el tiempo?",
            "Escribo en dos idiomas para pensar dos veces sobre lo mismo.",
            "Formalizar una intuición es el paso que casi nadie da, y donde aparece el valor.",
            "Tratar un tema filosófico como problema de diseño cambia las preguntas y las respuestas.",
            "La estética no decora: comunica jerarquía, intención y oficio.",
        ],
    },
    "web": {
        "label": "DESARROLLO WEB",
        "hashtags": ["#DesarrolloWeb", "#Rendimiento", "#Frontend"],
        "subs": ["Rendimiento y base sólida", "Web que se siente bien", "Del HTML al LCP"],
        "items": [
            "El LCP no mejora con más presupuesto de servidor, sino enviando menos bytes y menos bloqueos.",
            "El layout shift se arregla en el marcado: `width`, `height` y reservar espacio para medios.",
            "HTML semántico es la optimización más barata que existe: mejora SEO, accesibilidad y mantenibilidad a la vez.",
            "Cachear con `stale-while-revalidate` da respuesta instantánea y actualización en segundo plano.",
            "Una fuente variable bien subseteada pesa menos que dos pesos estáticos y da mejor tipografía.",
            "CSS lógico (`margin-inline`, `padding-block`) soporta RTL sin duplicar reglas.",
            "`prefers-reduced-motion` no es opcional: respeta la decisión del usuario y evita mareos.",
            "Validación en cliente para feedback rápido, en servidor para confiabilidad: no es una u otra.",
            "INP suele doler más que LCP: revisa listeners pesados en interacciones frecuentes.",
            "Un service worker mal usado sirve versiones viejas durante días; bien usado, da resiliencia offline.",
            "`fetchpriority=\"high\"` en la imagen hero mejora LCP sin tocar infraestructura.",
            "La página debe funcionar sin JavaScript; lo demás es mejora progresiva.",
            "Cachear HTML, hashear assets y medir con datos de campo, no con laboratorio.",
            "Cada `div` extra es una decisión de accesibilidad, rendimiento y mantenimiento.",
            "El estado en la URL hace la interfaz compartible y la navegación predecible.",
            "Medir INP, CLS y LCP una vez al mes evita sorpresas y conversaciones incómodas.",
        ],
    },
    "accesibilidad": {
        "label": "ACCESIBILIDAD",
        "hashtags": ["#Accesibilidad", "#A11y", "#DiseñoInclusivo"],
        "subs": ["Diseñar para todos", "Accesibilidad accionable", "Sin barreras, con criterio"],
        "items": [
            "Contraste mínimo 4.5:1 en texto normal y 3:1 en texto grande; los placeholders suelen fallar.",
            "Un foco visible y coherente es la base: si lo apagas, alguien no puede navegar.",
            "Los `aria-label` no arreglan una mala estructura: primero HTML semántico.",
            "La navegación por teclado se prueba con Tab, Shift+Tab, Enter y Espacio; cinco minutos revelan mucho.",
            "Un `lang` correcto hace que el lector de pantalla cambie de voz y pronuncie bien.",
            "El texto alternativo describe la función de la imagen, no \"imagen de\".",
            "Los errores deben explicar qué pasó y cómo resolverlo, asociados al campo correcto.",
            "Un skip link al contenido principal cuesta veinte minutos y ahorra cientos de tabulaciones.",
            "Un modal necesita foco atrapado, cierre con Escape y devolución del foco al disparador.",
            "Los estados no pueden depender solo del color: añade texto, icono o patrón.",
            "Respetar `prefers-reduced-motion` también es accesibilidad, no solo comodidad.",
            "Probar con lector de pantalla una vez al mes cambia cómo diseñas para siempre.",
            "Etiquetas visibles: el placeholder desaparece al escribir y no es una etiqueta.",
            "La accesibilidad se diseña, no se parchea al final del sprint.",
            "Contenido claro y frases cortas también son accesibilidad cognitiva.",
            "Un error de accesibilidad es un error de producto, no un extra opcional.",
        ],
    },
    "usabilidad": {
        "label": "USABILIDAD",
        "hashtags": ["#Usabilidad", "#UX", "#DiseñoDeProducto"],
        "subs": ["Menos fricción, más flujo", "Usabilidad medible", "Diseño que se entiende"],
        "items": [
            "Si hay que explicar el botón de guardar, el problema es el diseño, no el usuario.",
            "Reconocer es más fácil que recordar: opciones visibles y menús con criterio.",
            "Un formulario más corto convierte más que un formulario más bonito.",
            "El estado vacío es la primera impresión de tu producto: cuídalo.",
            "Cada acción necesita una reacción visible en menos de 100 ms: la interfaz debe tener pulso.",
            "Con cinco usuarios se detecta el 80% de los problemas de usabilidad.",
            "El texto de un botón debería ser un verbo concreto, no \"Aceptar\".",
            "Mide tareas completadas, no clics; los clics sin contexto engañan.",
            "Los patrones conocidos ahorran aprendizaje: innova donde realmente importa.",
            "Si el buscador no perdona un error tipográfico, todavía no está terminado.",
            "La carga cognitiva se acumula: cada decisión nueva tiene un coste para el usuario.",
            "Un buen error dice qué pasó, qué puede hacer el usuario y cómo continuar.",
            "El onboarding no reemplaza a un diseño comprensible desde el minuto uno.",
            "Lo que no se puede deshacer debe poder confirmarse antes.",
            "Diseña para el peor día del usuario, no para su mejor momento.",
            "La usabilidad se nota en soporte: cada ticket es una pista de diseño.",
        ],
    },
    "programacion": {
        "label": "PROGRAMACIÓN",
        "hashtags": ["#Programación", "#CleanCode", "#IngenieríaDeSoftware"],
        "subs": ["Oficio y criterio", "Código que se leerá", "Fundamentos que duran"],
        "items": [
            "El código se lee muchas más veces de las que se escribe: optimiza para quien lo lea en seis meses.",
            "Nombrar bien es la mitad de diseñar: `data`, `info` y `temp` esconden decisiones.",
            "Una función que hace dos cosas obliga a probar cuatro escenarios.",
            "Los tests que más valor dan describen comportamiento crítico, no cobertura.",
            "Duplicar está bien dos veces; a la tercera, abstrae con evidencia.",
            "\"Funciona en mi máquina\" se arregla con entornos reproducibles, no con fe.",
            "Un commit cuenta una historia: qué cambia y por qué, en la línea de asunto.",
            "Un error que se traga la causa original es deuda técnica emocional.",
            "Revisar código es enseñar; aprobar sin comentar desperdicia contexto.",
            "Escribe el contrato antes que la implementación: aclara el diseño.",
            "Si no puedes explicarlo en una frase, todavía no lo entiendes del todo.",
            "Refactoriza con red: tests primero, cambios pequeños después.",
            "La deuda técnica es un préstamo: decide cuándo pagas intereses.",
            "Optimiza después de medir; antes de medir es adivinar.",
            "Los logs son para el tú del futuro: escríbelos como si tuvieras prisa.",
            "La simplicidad no es hacer menos: es quitar lo que sobra.",
        ],
    },
    "javascript": {
        "label": "JAVASCRIPT",
        "hashtags": ["#JavaScript", "#WebDevelopment", "#Frontend"],
        "subs": ["JS moderno, sin ruido", "El lenguaje, bien usado", "Detalles del runtime"],
        "items": [
            "`structuredClone` ya es estándar para copias profundas: olvida los trucos con JSON.",
            "`??` solo trata `null` y `undefined`; `||` también cae con `0`, `\"\"` y `false`.",
            "`Object.hasOwn`, `at(-1)` y `groupBy`: el JavaScript moderno que ya puedes usar sin librerías.",
            "Los módulos ES tienen ámbito propio: adiós a las variables globales accidentales.",
            "`Promise.allSettled` es para lotes donde un fallo no debe tumbar el resto.",
            "`AbortController` convierte la cancelación en código limpio, también en `fetch`.",
            "`Intl` resuelve números, fechas y plurales sin dependencias de localización.",
            "Los campos privados con `#` dan encapsulación real, no de convención.",
            "El orden de la cola de microtareas explica el 90% de los bugs async \"imposibles\".",
            "Los generadores permiten procesar datos en streaming sin cargar todo en memoria.",
            "Un `WeakMap` para metadatos evita fugas de memoria que el profiler no ve.",
            "`Array.fromAsync` convierte flujos asíncronos en arrays legibles.",
            "Top-level await simplifica la inicialización, pero bloquea: úsalo con intención.",
            "Un `switch` sin `break` no es un misterio: es un error esperando silencio.",
            "`for await` versus cargar todo: decide por tamaño de datos, no por gusto.",
            "Los getters pueden esconder trabajo pesado: úsalos con responsabilidad.",
        ],
    },
    "vscode": {
        "label": "VS CODE",
        "hashtags": ["#VSCode", "#Productividad", "#DesarrolloWeb"],
        "subs": ["Editor afilado", "Atajos que suman", "Flujo de trabajo"],
        "items": [
            "`Cmd/Ctrl+P` con `@` salta a símbolos del archivo y ahorra cientos de scrolls al día.",
            "Los perfiles de VS Code separan trabajo, estudio y charlas sin mezclar extensiones.",
            "Settings Sync devuelve un entorno idéntico en cinco minutos.",
            "`tsc --watch` más el panel de Problems sustituyen media hora de idas y venidas.",
            "`formatOnSave` solo brilla si la configuración vive en el repositorio.",
            "Los multi-root workspaces permiten trabajar en un monorepo sin abrir tres ventanas.",
            "`git blame` inline y el Timeline responden quién cambió qué sin salir del editor.",
            "Los tasks integrados convierten \"corre los tests\" en una combinación de teclas.",
            "Remote SSH y Remote Containers desarrollan en el entorno real sin ensuciar tu máquina.",
            "Un `settings.json` versionado alinea al equipo sin discusiones de estilo.",
            "Zen mode y centrar el layout: menos ventana, más foco.",
            "`code --diff a b` compara archivos al instante, sin herramientas externas.",
            "Snippets propios: escribe el boilerplate una vez y olvídate.",
            "`search.exclude` acelera las búsquedas en proyectos enormes.",
            "Perfiles de terminal por proyecto ahorran cambios de contexto.",
            "Sticky scroll y breadcrumbs te orientan en archivos largos sin perder el hilo.",
        ],
    },
    "extensiones": {
        "label": "EXTENSIONES VS CODE",
        "hashtags": ["#VSCode", "#Extensiones", "#OpenSource"],
        "subs": ["Del editor al mercado", "Automatizar sin estorbar", "APIs y detalle"],
        "items": [
            "Una extensión debe fallar en silencio o avisar claro; nunca dejar la sensación de \"no funciona\".",
            "`engines.vscode` evita llamar APIs que no existen en la versión del usuario.",
            "La activación perezosa importa: tu extensión no debe arrancar el editor más lento.",
            "Los comandos deben ser idempotentes: ejecutar dos veces no puede duplicar estado.",
            "`OutputChannel` para logs: `console.log` se pierde en cuanto se cierra el panel.",
            "Un README con GIF y atajos multiplica las instalaciones más que una feature oculta.",
            "Las cláusulas `when` hacen que tu comando aparezca solo en contextos válidos.",
            "Los tests con `vscode-test` simulan al usuario y atrapan regresiones reales.",
            "Publicar con `vsce` y versionado semántico: el marketplace castiga versiones rotas.",
            "Un icono legible a 24 px vale más que un logo detallado.",
            "Telemetría opcional y anónima: medir sí, invadir no.",
            "WebView solo cuando el árbol nativo no alcanza.",
            "CHANGELOG por versión: es la documentación que sí se lee.",
            "Valores por defecto sensatos: cero configuración para empezar a usarla.",
            "Localización con `l10n`: el marketplace es global por defecto.",
            "Responder issues en 48 horas: la comunidad es parte del producto.",
        ],
    },
    "ecosistema": {
        "label": "ECOSISTEMA DEV",
        "hashtags": ["#DevTools", "#OpenSource", "#Productividad"],
        "subs": ["Tooling sin drama", "Stack coherente", "Dependencias bajo control"],
        "items": [
            "pnpm más workspaces resuelve enlaces deterministas y deduplicación en monorepos grandes.",
            "Biome y oxlint aparecen cuando ESLint se convierte en cuello de botella.",
            "Vitest reutiliza tu configuración de Vite: deja de mantener dos mundos.",
            "Turborepo y Nx: elige por caché y orquestación, no por moda.",
            "`engines` en package.json documenta y bloquea la versión real de Node.",
            "Renovate bien configurado reduce el ruido de PRs y mantiene dependencias al día.",
            "tsup o esbuild para librerías: builds en milisegundos y binarios pequeños.",
            "ESM primero, CJS por compatibilidad: planifica la doble salida con estrategia.",
            "`corepack` fija el gestor de paquetes por proyecto sin instalaciones globales.",
            "Un lockfile consistente en CI garantiza que todos ejecutan exactamente lo mismo.",
            "Los devcontainers convierten \"instala esto\" en abrir un contenedor.",
            "`npm audit --audit-level=high` en CI, no cuarenta avisos informativos.",
            "Un script `check` que corre tipos, lint y tests: una sola puerta de entrada.",
            "Monorepo sí, pero con límites: paquetes con dueño y contrato claro.",
            "Versionado semántico real: los breaking changes se anuncian, no se descubren.",
            "Menos dependencias: cada una es una promesa que mantiene otra persona.",
        ],
    },
    "distros": {
        "label": "LINUX / DISTROS",
        "hashtags": ["#Linux", "#Distros", "#OpenSource"],
        "subs": ["Linux de diario", "Escritorio como herramienta", "Rolling con red"],
        "items": [
            "Hyprland combina Wayland, tiling y atajos: el escritorio como herramienta.",
            "Debian estable en servidores: aburrido es un cumplido.",
            "Fedora adelanta tecnología; el usuario pone la disciplina.",
            "Arch no es difícil, es explícito: cada decisión te pertenece.",
            "openSUSE Tumbleweed con snapper da rolling release con red de seguridad.",
            "NixOS convierte la configuración del sistema en código reproducible.",
            "Mint para empezar, Ubuntu LTS para soporte, Arch para control.",
            "El mejor distro combina tus drivers, tu flujo y tu tolerancia al cambio.",
            "Un snapshot antes de actualizar son diez minutos que salvan una tarde.",
            "KDE Plasma 6 en Wayland ya es una opción de diario para muchos perfiles.",
            "Un live USB prueba hardware y decisiones antes de instalar nada.",
            "Dotfiles versionados: cambiar de distro es una tarde, no un drama.",
            "Repositorios oficiales primero; PPAs y AUR con criterio y lecturas.",
            "Wayland no es futuro: es presente con matices según hardware.",
            "Un sistema limpio se nota en el arranque: mide, no supongas.",
            "Cada distro enseña algo; elige la que te enseñe lo que te falta.",
        ],
    },
    "carrera": {
        "label": "CARRERA DEV",
        "hashtags": ["#CarreraProfesional", "#DesarrolloProfesional", "#AprenderEnPúblico"],
        "subs": ["Seniority real", "Carrera con criterio", "Aprender a propósito"],
        "items": [
            "Tu portfolio es el README de tu criterio: muestra decisiones, no capturas.",
            "Aprender en público acelera más que esperar a ser experto para escribir.",
            "Escribir bien y leer código ajeno es la mejor inversión temprana.",
            "Un CV elige una historia; no puede contarlo todo.",
            "De junior a senior se pasa tomando decisiones y explicándolas, no acumulando frameworks.",
            "Los fundamentos duran más que cualquier versión de cualquier librería.",
            "Pide feedback concreto: \"¿qué cambiarías de esta decisión?\" rinde más que \"¿lo hice bien?\".",
            "La entrevista evalúa comunicación bajo presión: practícala en voz alta.",
            "Documenta lo que aprendes en el trabajo; es tu mejor material de portfolio.",
            "El síndrome del impostor se combate publicando con honestidad, no estudiando en secreto.",
            "Un poco de diseño, accesibilidad y producto multiplica tu impacto como dev.",
            "Treinta minutos diarios ganan a un curso intensivo de fin de semana.",
            "Decir \"no sé\" con criterio genera más confianza, no menos.",
            "Los hábitos se notan a cinco años; las herramientas, a cinco días.",
            "Especializarse no es cerrarse: profundidad con contexto resuelve problemas reales.",
            "Escribe post-mortems de tus proyectos: los errores documentados valen oro.",
        ],
    },
}

# Interleaving order (consecutive posts never repeat a topic).
ORDER = ["xscriptor", "typescript", "web", "accesibilidad", "usabilidad",
         "programacion", "javascript", "vscode", "extensiones", "ecosistema",
         "distros", "carrera"]

CLOSERS = [
    "¿Cómo lo resuelves en tu equipo?",
    "¿Te ha pasado? Cuéntame tu caso.",
    "¿Añadirías algo a la lista?",
    "¿Qué herramienta usas tú para esto?",
    "¿Estás de acuerdo o lo ves distinto?",
    "¿Cuál es tu experiencia?",
    "¿Qué me falta por aprender aquí?",
    "Si trabajas en esto, ¿qué matiz añadirías?",
    "¿Lo has probado? Me interesa tu experiencia.",
    "¿Qué otro patrón te ha funcionado?",
    "¿Qué decisión tomaste tú en un caso así?",
    "¿Se te ocurre un caso donde esto falle?",
    "¿Cómo lo enseñas tú?",
    "¿Qué priorizas cuando toca decidir?",
    "¿Te suena? Comenta tu experiencia.",
    "¿Hay algún punto que matizarías?",
    "¿Qué recomendarías a quien empieza?",
    "¿Cuál es tu atajo favorito para esto?",
    "¿Qué te gustaría ver más a fondo?",
    "Intercambio de ideas: ¿cómo lo harías tú?",
    "¿Qué te sorprendió de esto?",
    "¿Tienes un ejemplo propio?",
]

OPENERS = [
    "Lo veo cada semana en proyectos reales:",
    "Me lo preguntan a menudo, así que lo dejo por escrito:",
    "Se repite en casi todas las revisiones de código:",
    "Después de años tocando esto, resumo lo que funciona:",
    "Poca gente lo dice así, pero es la base:",
    "Este patrón aparece una y otra vez:",
    "Lo aprendí a base de equivocarme:",
    "Concreto y sin rodeos:",
    "Si tuviera que resumirlo para alguien que empieza:",
    "La diferencia entre hacerlo y hacerlo bien está aquí:",
    "Cuatro ideas que cambian el resultado:",
    "Esto es lo que aplico por defecto:",
]

WINDOWS = ["Miércoles 16:00", "Viernes 15:30", "Martes 12:30", "Jueves 8:00",
            "Jueves 13:00", "Miércoles 15:30", "Viernes 16:00", "Martes 9:00"]
